### ISSUE TITLE
Correct extensions resolution order?

### ISSUE THREAD

**Issue by romkhub** [VitorLuizC/ts-jest-resolver#5]
I checked how TS resolves `.js`,`.jsx`,`.mjs` and `.cjs` imports.
For `.cjs` and `.mjs` it simply prefers TS version over a vanilla one, no issue here.
For both `.js` and `.jsx` import though, this is the resolution order I see - `.ts`, `.tsx`, `.js`, `.jsx` - so it looks for non-extended TS/JS at first.
I see this ordering was already corrected once here - https://github.com/VitorLuizC/ts-jest-resolver/commit/89afc07ccef62fc2a7b59d73c5e83af566a39349 - and this makes me even more curious on how things should actually be set.

In my experiment I used `typescript@4.9.5`, `"module": "node16"` in `tsconfig.json`, `"type": "module"` in `package.json`.

I'm not sure the order I see in my setup is a single correct one, but I see divergence over different tools:
- for example [ts-node looks for non-X versions at first, but by default it prefers vanilla JS over TS](https://github.com/TypeStrong/ts-node/blob/6b1fd40d91dd8771e7de04dc4347d0319f40ae3f/src/file-extensions.ts#L111) - this is configurable via [preferTsExts](https://typestrong.org/ts-node/docs/options#prefertsexts) though
- webpack allows configuring the exact order via [resolve.extensionAlias](https://webpack.js.org/configuration/resolve/#resolveextensionalias)
- (AFAIK) `typescript` and `ts-jest-resolver` don't allow configuring the order

Logging this not to say the existing resolution is incorrect, but rather to discuss.
Could you recall, why `ts-jest-resolver` puts its preference to -x extensions over vanilla ones?

P.S.: things become even trickier if we add conditional exports/imports and self-references into the equation, so chasing consistency over different setups feels like a rat-race and I feel it might worth requesting support from TS-team on these, resolution-related matters.

**Comment by VitorLuizC** [comment]
Ouch, that is probably my mistake. This library supposes to preserve TypeScript behavior regarding module resolution.

**Comment by VitorLuizC** [comment]
I've changed the import order to preserve TS behavior and published this as fix in the `v2.0.1` version.
